# Generated by Django 5.0.6 on 2024-06-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='tittle',
            new_name='title',
        ),
    ]
